version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    #build: .
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=iam,lambda,s3,dynamodb
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - ./init-scripts:/docker-entrypoint-initaws.d